org: rsmbryson
app: ntad-db
service: ntad-data
frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'stg'}
  stackName: ${self:provider.stage}-${self.service}
  stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "secretsmanager:GetSecretValue"
            - "lambda:InvokeFunction"
          Resource: "*"


functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 day)
