org: rsmbryson
app: ntad-db
service: ntad-data
frameworkVersion: '3'
configValidationMode: error
plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}

custom:
  environment: ${file(./environment.yml):${self:provider.stage}}
  pythonRequirements:
    dockerizePip: true

functions:
  pg2shp:
    handler: handler.run
    events:
      - schedule: rate(1 day)
    environment:
      AGOL_URL: 'https://xentity.maps.arcgis.com/'
      AGOL_USER: ${ssm:/agol-user~true}
      AGOL_PASS: ${ssm:/agol-pass~true}

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ntadbucket
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
